---
name: Unit Testing for TerraformTaskV4
on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  unit-test:
    name: Unit Test V4 Task
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Run Unit Tests
      run: |
        node -v
        npm -v
        npm install -g typescript
        npm install -g mocha
        tsc -v
        cd Tasks/TerraformTask/TerraformTaskV4
        npm install -include=dev
        npm test
