---
name: Unit Testing for TerraformTaskV4
on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  unit-test:
    name: Unit Test V4 Task
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Run Unit Tests
      run: |
        cd Tasks/TerraformTask/TerraformTaskV4
        npm install -include=dev
        node -v
        npm -v

        npm test

        ls src
        ls Tests
        ls node_modules
